### ISSUE TITLE
May the pseudo c++ be re-written in c++

### ISSUE THREAD

**Issue by moe123** [google/exposure-notifications-internals#14]
Hello,

may the pseudo c++cruft  be actually re-written in proper c++? not in a garble mix of C calls and very fragile c++ paradigm understanding as well as C, hence the mix of both will be out of scope of any possible criticism here.

Thank you.

**Comment by nic0lette** [comment]
Hi,

Thanks for the comment. Do you mean in the docs? Could you provide an example of what you mean?

**Comment by moe123** [comment]
Hello,

I can understand that you are personally upset; and even, you are supposed to be a seasoned engineer. That is not about any documentation or I don't know what proper kind of mind invention we could spell out here, but, nonetheless at "most", the "code" illegitimately occupying the folder labeled "cpp" within this repository. Can't make it more clear., I think?

Thank you.

**Comment by ljl-covid** [comment]
@moe123 actually that's not clear at all, except for the fact you are clearly being gratuitously rude.
