### ISSUE TITLE
Please clarify the Federation "Traveller" concept

### ISSUE THREAD

**Issue by mh-** [google/exposure-notifications-internals#24]
In the context of federation between different EN servers, there's the "traveller" concept.
Apparently this indicates whether a user travelled to another country while using EN.
Apparently this information is somehow generated by the user's device - but where? 
[The API description](https://developers.google.com/android/exposure-notifications/exposure-notifications-api#data-structures) does not mention `traveller`, although it might be part of `TemporaryExposureKey` - 
or it could be the task of the app, to determine whether the user is in their home country or travelling?

This all seems to be undocumented at the moment, although federation is already in production.

Since this could be perceived as location tracking of users ("is the user staying in the home country or not?"), it is probably of interest to users to understand how this is handled. 
Could you please clarify this topic, or point to the place where it's documented?

**Comment by mikehelmick** [comment]
The EN application prompts the user to ask if they have traveled in the last 14 days before upload keys.

**Comment by mh-** [comment]
Thanks for the clarification.
