### ISSUE TITLE
Reporting issues on Google Play services / Exposure Notifications service UI

### ISSUE THREAD

**Issue by MikeMcC399** [google/exposure-notifications-internals#3]
Is this an appropriate place to report User Interface issues for the Exposure Notifications service under Google Play services?

I'm referring to what is shown on an Android device after selecting Settings > Google > COVID-19 exposure notifications.

If this is not a good place for such reports / discussions, if there some other place which is recommended?

Many thanks!

**Comment by nic0lette** [comment]
Hi,

Thanks for your question. Unfortunately this is not a great place to report or discuss such issues. The best advice I can provide is that these issues should be shared with the Public Health Authority/App developer in your region.  Those partners. can then share that feedback with Google via their DevRel contacts.

**Comment by MikeMcC399** [comment]
@nic0lette 
Thank you for your advice. I was already addressing the issues through the German app developer, but so far did not get any feedback there. I will be patient and keep to reporting through the channel you recommend.
