### ISSUE TITLE
Receiver-side functionality missing

### ISSUE THREAD

**Issue by doug-leith** [google/exposure-notifications-internals#4]
Thanks for posting this code.  Regarding Bluetooth, it seems to essentially include only the transmission functionality (construction of beacon payloads etc).   Most of that is already pretty well described in existing documentation.    I'd say it is important to also include the Bluetooth receive-side code, i.e. the code that receives Bluetooth beacons and calculates attenuation values, scanning instances, exposure duration times and so on, since this has a v direct impact of the generation of exposure notifications.

**Comment by nic0lette** [comment]
Thank you for your input.  I believe [Apple's implementation](https://developer.apple.com/exposure-notification/) includes this code, which may be helpful in the meantime.

**Comment by nic0lette** [comment]
I recently added this code in the [updates](https://github.com/google/exposure-notifications-internals/commit/413b561f59cd4a63b571cac83821959e6e022ce8) change, so I'll close this out for now.
