### ISSUE TITLE
compile error 

### ISSUE THREAD

**Issue by sixperson** [google/exposure-notifications-internals#7]
![image](https://user-images.githubusercontent.com/35401022/88522036-66c9ec80-d028-11ea-8a39-f77299188eb9.png)
what's wrong?thanks

**Comment by nic0lette** [comment]
Hi,
Sorry, but building this on Windows is not supported. In addition, while it is possible to build this code, the app it creates doesn't actually do anything. If it's important for you to get it to compile, then I'd take a look at the path separators.
